"""Sample data used when DEMO_MODE is on (no NPM credentials configured yet),
so the dashboard is useful to look at immediately after first deploy."""

DEMO_PROXY_HOSTS = [
    {
        "id": 1,
        "domain_names": ["office-dev.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.4.104",
        "forward_port": 8081,
        "certificate_id": 0,
        "ssl_forced": False,
        "enabled": True,
    },
    {
        "id": 2,
        "domain_names": ["tenant-mgmt-dev.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.4.104",
        "forward_port": 8090,
        "certificate_id": 0,
        "ssl_forced": False,
        "enabled": True,
    },
    {
        "id": 3,
        "domain_names": ["api-dev.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.4.104",
        "forward_port": 8899,
        "certificate_id": 0,
        "ssl_forced": False,
        "enabled": True,
    },
    {
        "id": 4,
        "domain_names": ["vitalhealth.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.4.104",
        "forward_port": 8899,
        "certificate_id": 1,
        "ssl_forced": True,
        "enabled": True,
    },
    {
        "id": 5,
        "domain_names": ["acmehomehealth.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.4.104",
        "forward_port": 8899,
        "certificate_id": 1,
        "ssl_forced": True,
        "enabled": True,
    },
    {
        "id": 6,
        "domain_names": ["docs.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.7.50",
        "forward_port": 85,
        "certificate_id": 1,
        "ssl_forced": True,
        "enabled": True,
    },
    {
        "id": 7,
        "domain_names": ["chat.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.4.104",
        "forward_port": 8065,
        "certificate_id": 1,
        "ssl_forced": True,
        "enabled": True,
    },
    {
        "id": 8,
        "domain_names": ["mcp-chat.smarrtcare.com"],
        "forward_scheme": "http",
        "forward_host": "192.168.4.104",
        "forward_port": 8066,
        "certificate_id": 0,
        "ssl_forced": False,
        "enabled": False,
    },
]

DEMO_REDIRECTION_HOSTS = []
DEMO_STREAMS = []
DEMO_VERSION = "demo"
